### ISSUE TITLE
Split library into two packages.

### ISSUE THREAD

**Issue by bodia-uz** [wix/okidoc#13]
Split library into two packages in one monorepo:
- okidoc
- okidoc-site

Not all users need a generation of md files. We need allow use `okidoc-site` as separate lib.

Mb we need a separate package like `okidoc-md`(or your variant instead of `md`), which only generates `md` files from source. Then `okidoc` lib will be preset of `[okidoc-md, okidoc-site]`

/cc @kupriyanenko @BrooklynKing

**Comment by kupriyanenko** [comment]
I'm totally agree with it. We need to have 3 repos: `okidoc`, `okidoc-md` (maybe `okidoc-md-js`), `okidoc-site`.
