### ISSUE TITLE
Parsing interface with `new` in it

### ISSUE THREAD

**Issue by BrooklynKing** [wix/okidoc#59]
```ts
interface IPlaybackAdapterClass {
  new (eventEmitter: IEventEmitter): IPlaybackAdapter;

  isSupported(): boolean;
}
```

when okidoc trying to parse this construction with babylon(?), it fails with exception
```
An error occurred while building documentation. { SyntaxError: "Player public methods" documentation source (src/core/default-modules.ts) - Unexpected token (82:2)
  80 | interface IPlaybackAdapterClass {
  81 |   new (eventEmitter: IEventEmitter): IPlaybackAdapter
> 82 |   isSupported(): boolean;
     |  ^
  83 | }
  84 |
  85 | /**
```

as you can see, there is no `;` after line with `new`. Right now i'm just putting this line as last in interface declaration, so it's not critical for me.

**Comment by bodia-uz** [comment]
Thanks for reporting. Will look into it

**Comment by skyiea** [comment]
Pending resolution of https://github.com/babel/babel/pull/10258
Then we'll need to update `@babel/generator` in `okidoc-md/package.json`.
